# Generated by Django 4.2.4 on 2024-01-25 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
