# Generated by Django 4.2.4 on 2024-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_app", "0002_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("additionalField1", models.CharField(max_length=100)),
                ("additionalField2", models.CharField(max_length=100)),
                ("additionalField3", models.CharField(max_length=100)),
                ("additionalField4", models.CharField(max_length=100)),
                ("additionalField5", models.CharField(max_length=100)),
            ],
        ),
    ]
