# Generated by Django 4.2.4 on 2024-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_app", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
