# Generated by Django 4.2.4 on 2024-01-26 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_app", "0004_alter_product_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Add_Product",
        ),
    ]
