# Generated by Django 4.2.4 on 2024-01-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_app", "0005_rename_product_add_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "any_disease",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("allergies", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
