# Generated by Django 4.2.4 on 2024-01-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_app", "0006_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordered_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("size", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
