# Generated by Django 4.2.4 on 2024-01-29 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_app", "0008_wallet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
