# Generated by Django 4.2.4 on 2024-01-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "any_disease",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("allergies", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("debit_card", "Debit Card"),
                            ("credit_card", "Credit Card"),
                            ("upi", "UPI"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
