# Generated by Django 4.2.4 on 2024-01-30 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fit_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steps_count", models.PositiveIntegerField()),
                ("calories_burn", models.PositiveIntegerField()),
                ("rewards", models.CharField(max_length=255)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("registration_date_time", models.DateTimeField(auto_now_add=True)),
                ("age", models.PositiveIntegerField()),
                (
                    "username",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
