# Generated by Django 4.2.4 on 2024-01-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fit_app", "0002_add_reward"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("steps_count", models.PositiveIntegerField()),
                ("calories_burn", models.PositiveIntegerField()),
                ("rewards", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
